<x-app-layout>
    <x-slot name="header">{{ __('app.overview') }}</x-slot>
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="mb-2 text-xs font-semibold uppercase tracking-widest text-emerald-700">{{ __('app.'.$role) }}</p><h1 class="page-title">{{ __('app.welcome', ['name' => auth()->user()->name]) }}</h1><p class="muted mt-2">{{ __('portal.dashboard_note') }}</p></div><div class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-500">{{ __('app.today') }} <span class="ms-2 font-medium text-slate-700" dir="ltr">{{ now()->format('Y-m-d') }}</span></div></div>
    @if($quickActions->isNotEmpty())<section class="flex flex-wrap items-center gap-2" aria-label="{{ __('portal.quick_actions') }}">@foreach($quickActions as $action)<a href="{{ route($action[2]) }}" class="btn-secondary"><x-icon :name="$action[4]" class="h-4 w-4"/>{{ __('portal.'.$action[3]) }}</a>@endforeach</section>@endif
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as $metric)<div class="card min-w-0 p-5"><div class="flex items-start justify-between gap-3"><p class="text-xs font-medium leading-5 text-slate-500">{{ __('portal.'.$metric['label']) }}</p><span class="rounded-xl bg-emerald-50 p-2 text-emerald-700"><x-icon :name="$metric['icon']" class="h-4 w-4"/></span></div><p class="mt-4 break-words text-2xl font-semibold tabular-nums tracking-tight text-slate-900">{{ $metric['value'] }}</p>@if($metric['route'])<a href="{{ route($metric['route']) }}" class="text-link mt-4 inline-flex items-center gap-1 text-xs">{{ __('app.view_all') }}<x-icon name="arrow" class="h-3 w-3 rtl:rotate-180"/></a>@endif</div>@endforeach</div>
    <div class="grid items-start gap-6 xl:grid-cols-2">
        @can('payments.view')<x-card :title="__('app.recent_payments')"><x-slot name="actions"><a href="{{ route('payments.index') }}" class="text-link text-xs">{{ __('app.view_all') }}</a></x-slot>
@if($payments->isEmpty())<x-empty-state/>@else<x-data-table :caption="__('app.recent_payments')" :headings="[__('portal.tenant'),__('app.amount'),__('app.due_date'),__('app.status')]">@foreach($payments as $payment)<tr><td><a href="{{ route('payments.show', $payment) }}" class="text-link">{{ $payment->tenant?->full_name }}</a></td><td><x-data-value :value="$payment->amount" column="amount"/></td><td>{{ $payment->due_date->format('Y-m-d') }}</td><td><x-badge :value="$payment->status"/></td></tr>@endforeach</x-data-table>@endif</x-card>@endcan
        @can('leases.view')<x-card :title="__('portal.ending_soon')">@forelse($endingLeases as $lease)<a href="{{ route('leases.show', $lease) }}" class="flex items-center justify-between gap-4 border-t border-slate-100 p-5 hover:bg-slate-50"><div class="min-w-0"><p class="text-sm font-semibold text-slate-900">{{ $lease->contract_number }}</p><p class="mt-1 truncate text-xs text-slate-400">{{ $lease->tenant?->full_name }} · {{ $lease->unit?->unit_number }}</p></div><span class="text-xs font-medium tabular-nums text-amber-700">{{ $lease->end_date->format('Y-m-d') }}</span></a>@empty<x-empty-state :title="__('portal.no_ending_leases')" :description="__('portal.dashboard_note')" icon="leases"/>@endforelse</x-card>@endcan
        @can('maintenance.view')
            <x-card :title="__('portal.requests_by_status')"><div class="space-y-5 p-6">@forelse($statusCounts as $status => $count)<div><div class="mb-2 flex items-center justify-between"><x-badge :value="$status"/><span class="text-sm font-semibold tabular-nums text-slate-800">{{ $count }}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100" aria-hidden="true"><div class="h-full rounded-full bg-emerald-500" style="width: {{ $requestTotal ? round($count / $requestTotal * 100) : 0 }}%"></div></div></div>@empty<x-empty-state/>@endforelse</div></x-card>
            <x-card :title="__('portal.recent_requests')">@forelse($requests as $request)<a href="{{ route('maintenance.show', $request) }}" class="flex items-center justify-between gap-4 border-t border-slate-100 p-5 hover:bg-slate-50"><span class="min-w-0 text-sm font-medium"><span class="block truncate">{{ $request->title }}</span><span class="mt-2 block text-xs text-slate-400">{{ $request->created_at->format('Y-m-d') }}</span></span><x-badge :value="$request->status"/></a>@empty<x-empty-state/>@endforelse</x-card>
            @can('buildings.view')<x-card :title="__('portal.maintenance_buildings')">@if($maintenanceBuildings->isEmpty())<x-empty-state/>@else<x-data-table :caption="__('portal.maintenance_buildings')" :headings="[__('portal.building'),__('portal.request_count')]">@foreach($maintenanceBuildings as $building)<tr><td><a href="{{ route('buildings.show', $building) }}" class="text-link">{{ $building->name }}</a></td><td class="font-semibold tabular-nums">{{ $building->maintenance_requests_count }}</td></tr>@endforeach</x-data-table>@endif</x-card>@endcan
        @endcan
    </div>
    @can('announcements.view')<section><h2 class="mb-4 font-semibold text-slate-900">{{ __('portal.latest_announcements') }}</h2><x-announcement-cards :announcements="$announcements"/></section>@endcan
</x-app-layout>
