<x-app-layout>
<x-slot name="breadcrumbs"><x-breadcrumbs :items="[__('app.tenants')=>route('tenants.index'), ($tenant->exists ? __('property.edit_tenant') : __('property.add_tenant'))=>null]"/></x-slot>
<x-page-header :title="$tenant->exists ? __('property.edit_tenant') : __('property.add_tenant')" :description="$tenant->exists ? __('property.edit_intro') : __('property.create_tenant_intro')" icon="tenants"/>
<form method="POST" action="{{ $tenant->exists ? route('tenants.update', $tenant) : route('tenants.store') }}" x-data="{ submitting: false }" @submit="submitting = true" class="space-y-6">@csrf @if($tenant->exists)@method('PUT')@endif
@if(auth()->user()->hasRole('super_admin') && !$tenant->exists)<x-form-section :title="__('property.company')" :description="__('property.company_hint')" icon="companies"><div class="sm:col-span-2"><x-select name="company_id" :options="$companies" required/></div></x-form-section>@endif
<x-form-section :title="__('property.personal_information')" :description="__('property.personal_information_hint')" icon="profile"><x-field name="full_name" :value="$tenant->full_name" maxlength="255" autofocus/><x-field name="national_id" label="property.attributes.national_id" :value="$tenant->national_id" :required="false" maxlength="100"/><x-field name="email" type="email" :value="$tenant->email" autocomplete="email" dir="ltr" maxlength="255"/><x-field name="phone" type="tel" :value="$tenant->phone" autocomplete="tel" dir="ltr" maxlength="40"/><div class="sm:col-span-2"><x-textarea name="address" :value="$tenant->address" maxlength="2000"/></div>@if($tenant->user_id)<p class="muted sm:col-span-2">{{ __('property.linked_account_hint') }}</p>@endif</x-form-section>
<x-form-section :title="__('property.emergency_contact')" :description="__('property.emergency_contact_hint')" icon="tenants"><x-field name="emergency_contact_name" label="property.attributes.emergency_contact_name" :value="$tenant->emergency_contact_name" :required="false" maxlength="255"/><x-field name="emergency_contact_phone" label="property.attributes.emergency_contact_phone" type="tel" :value="$tenant->emergency_contact_phone" :required="false" dir="ltr" maxlength="40"/></x-form-section>
<x-form-section :title="__('property.additional_notes')" :description="__('property.notes_hint')"><div class="sm:col-span-2"><x-textarea name="notes" :value="$tenant->notes" maxlength="5000"/></div></x-form-section>
<x-form-footer :cancel="$tenant->exists ? route('tenants.show', $tenant) : route('tenants.index')" :label="__('property.save_tenant')"/>
</form></x-app-layout>