<x-app-layout>
<x-slot name="breadcrumbs"><x-breadcrumbs :items="[__('app.tenants')=>route('tenants.index'), $tenant->full_name=>null]"/></x-slot>
<x-page-header :title="$tenant->full_name" :description="__('property.tenant_summary')" icon="tenants"><x-slot name="actions"><x-detail-actions :record="$tenant" module="tenants" :label="$tenant->full_name"/></x-slot></x-page-header>
<div class="grid items-start gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><div class="space-y-6"><x-card :title="__('property.personal_information')"><x-details-list :record="$tenant" :fields="['full_name','national_id','email','phone','address','notes']"/></x-card><x-card :title="__('property.emergency_contact')"><x-details-list :record="$tenant" :fields="['emergency_contact_name','emergency_contact_phone']"/></x-card></div>
@can('leases.view')<x-card :title="__('property.current_tenancy')">@if($currentLease)<div class="p-6"><div class="mb-5 flex items-center justify-between gap-2"><span class="rounded-xl bg-emerald-50 p-3 text-emerald-700"><x-icon name="units" class="h-6 w-6"/></span><x-badge :value="$currentLease->status"/></div><p class="text-xs text-slate-400">{{ __('property.current_unit') }}</p><p class="mt-1 text-2xl font-semibold text-slate-900">{{ $currentLease->unit?->unit_number }}</p><p class="muted mt-1">{{ $currentLease->unit?->building?->name }}</p><dl class="mt-5 space-y-4 border-t border-slate-100 pt-5">@foreach(['contract_number','monthly_rent','start_date','end_date'] as $column)<div class="flex flex-wrap justify-between gap-2 text-sm"><dt class="text-slate-400">{{ __('app.'.$column) }}</dt><dd><x-data-value :value="$currentLease->$column" :column="$column"/></dd></div>@endforeach</dl><a href="{{ route('leases.show', $currentLease) }}" class="btn-secondary mt-6 w-full">{{ __('app.view') }}<x-icon name="arrow" class="h-4 w-4 rtl:rotate-180"/></a></div>@else<x-empty-state :title="__('property.no_current_lease')" :description="__('property.no_current_lease_hint')" icon="leases"/>@endif</x-card>@endcan
</div>
@if($leases)<x-card :title="__('property.related_leases')"><x-record-table :records="$leases" :columns="['contract_number','start_date','end_date','monthly_rent','status']" module="leases" :title="__('app.leases')"/></x-card>@endif
@if($payments)<x-card :title="__('property.related_payments')"><x-record-table :records="$payments" :columns="['amount','due_date','paid_at','status']" module="payments" :title="__('app.payments')"/></x-card>@endif
@if($maintenanceRequests)<x-card :title="__('property.related_maintenance')"><x-record-table :records="$maintenanceRequests" :columns="['title','priority','preferred_date','status']" module="maintenance" :title="__('app.maintenance')"/></x-card>@endif
@if($documents)<x-card :title="__('property.related_documents')" :description="__('property.related_documents_hint')"><x-record-table :records="$documents" :columns="['title','document_type','created_at']" module="documents" :title="__('app.documents')"/></x-card>@endif
@can('delete', $tenant)<x-deletion-notice :reason="$deletionReason"/>@endcan
</x-app-layout>