<x-app-layout>
<x-slot name="breadcrumbs"><x-breadcrumbs :items="[__('app.units')=>route('units.index'), ($unit->exists ? __('property.edit_unit') : __('property.add_unit')) => null]"/></x-slot>
<x-page-header :title="$unit->exists ? __('property.edit_unit') : __('property.add_unit')" :description="$unit->exists ? __('property.edit_intro') : __('property.create_unit_intro')" icon="units"/>
@if($buildings->isEmpty())<x-card><x-empty-state :title="__('property.no_buildings')" :description="__('property.no_buildings_hint')" icon="buildings"><x-slot name="actions">@can('create', \App\Models\Building::class)<a href="{{ route('buildings.create') }}" class="btn-primary"><x-icon name="plus"/>{{ __('property.add_building') }}</a>@endcan</x-slot></x-empty-state></x-card>
@else<form method="POST" action="{{ $unit->exists ? route('units.update', $unit) : route('units.store') }}" x-data="{ submitting: false }" @submit="submitting = true" class="space-y-6">@csrf @if($unit->exists)@method('PUT')@endif
<x-form-section :title="__('property.unit_information')" :description="__('property.unit_information_hint')" icon="units"><x-select name="building_id" :options="$buildings" :value="$unit->building_id" required/><x-field name="unit_number" label="property.attributes.unit_number" :value="$unit->unit_number" maxlength="64"/><x-field name="floor" type="number" :value="$unit->floor" min="-20" max="200"/><x-select name="type" :options="['apartment'=>__('app.apartment'),'office'=>__('app.office'),'shop'=>__('app.shop'),'storage'=>__('app.storage')]" :value="$unit->type" required/></x-form-section>
<x-form-section :title="__('property.specifications')" :description="__('property.specifications_hint')" icon="units"><x-field name="bedrooms" label="property.attributes.bedrooms" type="number" :value="$unit->bedrooms" :required="false" min="0" max="100"/><x-field name="bathrooms" label="property.attributes.bathrooms" type="number" :value="$unit->bathrooms" :required="false" min="0" max="100"/><x-field name="area" label="property.attributes.area" type="number" :value="$unit->area" :required="false" min="0.01" max="99999999.99" step="0.01"/></x-form-section>
<x-form-section :title="__('property.rent_availability')" :description="__('property.rent_availability_hint')" icon="payments"><x-field name="rent_amount" label="property.attributes.rent_amount" type="number" :value="$unit->rent_amount" min="0" max="9999999999.99" step="0.01"/><x-select name="status" :options="['vacant'=>__('app.vacant'),'occupied'=>__('app.occupied'),'maintenance'=>__('app.maintenance'),'reserved'=>__('app.reserved')]" :value="$unit->status" required/></x-form-section>
<x-form-footer :cancel="$unit->exists ? route('units.show', $unit) : route('units.index')" :label="__('property.save_unit')"/>
</form>@endif</x-app-layout>