<x-app-layout>
<x-slot name="breadcrumbs"><x-breadcrumbs :items="[__('app.buildings') => route('buildings.index'), ($building->exists ? __('property.edit_building') : __('property.add_building')) => null]"/></x-slot>
<x-page-header :title="$building->exists ? __('property.edit_building') : __('property.add_building')" :description="$building->exists ? __('property.edit_intro') : __('property.create_building_intro')" icon="buildings"/>
<form method="POST" action="{{ $building->exists ? route('buildings.update', $building) : route('buildings.store') }}" x-data="{ submitting: false }" @submit="submitting = true" class="space-y-6">@csrf @if($building->exists)@method('PUT')@endif
@if(auth()->user()->hasRole('super_admin') && !$building->exists)<x-form-section :title="__('property.company')" :description="__('property.company_hint')" icon="companies"><div class="sm:col-span-2"><x-select name="company_id" :options="$companies" required/></div></x-form-section>@endif
<x-form-section :title="__('property.building_information')" :description="__('property.building_information_hint')" icon="buildings"><x-field name="name" label="property.attributes.name" :value="$building->name" maxlength="255" autofocus/><x-field name="code" label="property.attributes.code" :value="$building->code" maxlength="64"/><x-field name="total_floors" type="number" :value="$building->total_floors" min="0" max="200"/><x-select name="status" :options="['active'=>__('app.active'),'inactive'=>__('app.inactive')]" :value="$building->status" required/></x-form-section>
<x-form-section :title="__('property.location')" :description="__('property.location_hint')" icon="location"><x-field name="city" :value="$building->city" maxlength="120"/><x-field name="district" :value="$building->district" maxlength="120"/><div class="sm:col-span-2"><x-textarea name="address" :value="$building->address" required maxlength="2000"/></div></x-form-section>
<x-form-section :title="__('property.additional_notes')" :description="__('property.notes_hint')"><div class="sm:col-span-2"><x-textarea name="notes" :value="$building->notes" maxlength="5000"/></div></x-form-section>
<x-form-footer :cancel="$building->exists ? route('buildings.show', $building) : route('buildings.index')" :label="__('property.save_building')"/>
</form></x-app-layout>