<x-app-layout>
<x-slot name="breadcrumbs"><x-breadcrumbs :items="[__('app.buildings') => null]"/></x-slot>
<x-page-header :title="__('app.buildings')" :description="__('property.buildings_intro')" icon="buildings"><x-slot name="actions">@can('create', \App\Models\Building::class)<a href="{{ route('buildings.create') }}" class="btn-primary"><x-icon name="plus" class="h-4 w-4"/>{{ __('property.add_building') }}</a>@endcan</x-slot></x-page-header>
<div class="grid gap-4 sm:grid-cols-2"><x-stat-card :label="__('property.total_buildings')" :value="$total" icon="buildings" :hint="__('property.portfolio_snapshot')"/><x-stat-card :label="__('property.active_buildings')" :value="$active" icon="check" :hint="__('property.portfolio_snapshot')"/></div>
<x-card>
<form method="GET" action="{{ route('buildings.index') }}" class="grid items-end gap-4 border-b border-slate-100 p-5 sm:grid-cols-2 xl:grid-cols-[minmax(220px,2fr)_1fr_1fr_auto]"><x-field name="q" type="search" :label="'property.search'" :required="false" :value="$filters['q'] ?? ''" :placeholder="__('property.search_buildings')"/><x-select name="status" :options="['active' => __('app.active'), 'inactive' => __('app.inactive')]" :value="$filters['status'] ?? ''" :placeholder="__('property.all_statuses')"/><x-select name="city" :options="$cities" :value="$filters['city'] ?? ''" :placeholder="__('property.all_cities')"/><div class="flex items-center gap-2"><button class="btn-primary">{{ __('property.apply_filters') }}</button><a href="{{ route('buildings.index') }}" class="btn-secondary" aria-label="{{ __('property.clear_filters') }}"><x-icon name="close" class="h-4 w-4"/></a></div></form>
@if($buildings->isEmpty())<x-empty-state :title="$total ? __('property.no_results') : __('property.empty_buildings')" :description="$total ? __('property.no_results_hint') : __('property.empty_buildings_hint')" icon="buildings"/>
@else
<x-data-table :caption="__('app.buildings')" :headings="[__('property.attributes.name'), __('property.location'), __('app.units'), __('property.occupancy'), __('app.status'), __('app.actions')]">
@foreach($buildings as $building)<tr><td><a href="{{ route('buildings.show', $building) }}" class="flex items-center gap-3"><span class="rounded-xl border border-slate-200 bg-slate-50 p-3 text-emerald-700"><x-icon name="buildings"/></span><span><span class="block font-semibold text-slate-900">{{ $building->name }}</span><span class="mt-1 block text-xs text-slate-400">{{ $building->code }}</span></span></a></td><td><span class="block text-slate-800">{{ $building->city }}</span><span class="mt-1 block text-xs text-slate-400">{{ $building->district }}</span></td><td><span class="font-semibold tabular-nums text-slate-800">{{ $building->units_count }}</span></td><td><div class="mb-2 text-xs text-slate-500">{{ __('property.of_units', ['occupied' => $building->occupied_units_count, 'total' => $building->units_count]) }}</div><progress class="h-1.5 w-28 overflow-hidden rounded-full [&::-webkit-progress-bar]:bg-slate-100 [&::-webkit-progress-value]:bg-emerald-500 [&::-moz-progress-bar]:bg-emerald-500" value="{{ $building->occupied_units_count }}" max="{{ max(1, $building->units_count) }}" aria-label="{{ __('property.occupancy') }}"></progress></td><td><x-badge :value="$building->status"/></td><td><x-record-actions :record="$building" module="buildings" :label="$building->name"/></td></tr>@endforeach
</x-data-table><div class="p-5">{{ $buildings->links('components.pagination') }}</div>@endif
</x-card></x-app-layout>