<x-app-layout>
    <div class="flex flex-wrap items-center justify-between gap-4"><div><p class="mb-2 text-xs font-semibold uppercase tracking-widest text-emerald-700">{{ __('portal.portal') }}</p><h1 class="page-title">{{ __('portal.welcome', ['name' => auth()->user()->name]) }}</h1><p class="muted mt-2">{{ __('portal.intro') }}</p></div><a href="{{ route('maintenance.create') }}" class="btn-primary"><x-icon name="plus"/>{{ __('portal.request_repair') }}</a></div>
    <div class="grid gap-4 md:grid-cols-2">
        <section class="relative overflow-hidden rounded-2xl bg-slate-950 p-6 text-white sm:p-8"><span class="inline-flex items-center gap-2 text-xs text-emerald-300"><x-icon name="units"/>{{ __('portal.current_unit') }}</span>@if($lease?->unit)<h2 class="mt-6 text-3xl font-semibold">{{ $lease->unit->building?->name }}</h2><p class="mt-2 text-lg text-slate-300">{{ __('portal.unit') }} {{ $lease->unit->unit_number }}</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('tenant.unit') }}" class="btn bg-white/10 text-white hover:bg-white/20">{{ __('portal.view_unit') }}</a><a href="{{ route('tenant.lease') }}" class="btn text-emerald-300 hover:bg-white/5">{{ __('portal.view_lease') }}<x-icon name="arrow" class="h-4 w-4 rtl:rotate-180"/></a></div>@else<h2 class="mt-6 text-2xl font-semibold">{{ __('portal.no_unit') }}</h2><p class="mt-3 text-sm leading-7 text-slate-400">{{ __('portal.no_unit_hint') }}</p>@endif</section>
        <div class="grid gap-4">
            <x-card><div class="p-6"><p class="text-xs font-medium text-slate-500">{{ __('portal.next_payment') }}</p>@if($nextPayment)<div class="mt-3 flex flex-wrap items-center justify-between gap-3"><p class="text-3xl font-semibold tabular-nums text-slate-900">{{ number_format($nextPayment->amount, 2) }} <span class="text-sm font-normal text-slate-400">{{ __('app.sar') }}</span></p><a href="{{ route('payments.show', $nextPayment) }}" class="btn-secondary">{{ __('app.view') }}</a></div><p class="mt-3 text-xs text-slate-500">{{ __('app.due_date') }} · <span dir="ltr">{{ $nextPayment->due_date->format('Y-m-d') }}</span></p>@else<h2 class="mt-3 font-semibold text-slate-900">{{ __('portal.no_next_payment') }}</h2><p class="muted mt-2">{{ __('portal.no_next_payment_hint') }}</p>@endif</div></x-card>
            <a href="{{ route('payments.overdue') }}" @class(['card flex items-center justify-between gap-3 p-6', 'border-red-200 bg-red-50/40' => $overdueAmount > 0])><span class="text-sm text-slate-500">{{ __('portal.overdue_amount') }}</span><span class="text-xl font-semibold tabular-nums {{ $overdueAmount > 0 ? 'text-red-700' : 'text-slate-900' }}">{{ number_format($overdueAmount, 2) }} <span class="text-xs font-normal">{{ __('app.sar') }}</span></span></a>
        </div>
    </div>
    @if($lease)<div class="card flex flex-wrap items-center justify-between gap-4 p-5"><div class="flex items-center gap-3"><span class="rounded-xl bg-emerald-50 p-3 text-emerald-700"><x-icon name="leases"/></span><div><p class="text-xs text-slate-500">{{ __('portal.active_lease') }}</p><a href="{{ route('tenant.lease') }}" class="text-link mt-1 block">{{ $lease->contract_number }}</a></div></div><p class="text-sm tabular-nums text-slate-500">{{ $lease->start_date->format('Y-m-d') }} — {{ $lease->end_date->format('Y-m-d') }}</p><x-badge :value="$lease->status"/></div>@endif
    <x-card :title="__('portal.recent_requests')"><x-slot name="actions"><a href="{{ route('maintenance.index') }}" class="text-link text-xs">{{ __('app.view_all') }}</a></x-slot>
@forelse($requests as $request)<a href="{{ route('maintenance.show', $request) }}" class="flex items-center justify-between gap-4 border-t border-slate-100 p-5 hover:bg-slate-50"><span class="min-w-0"><span class="block truncate text-sm font-semibold text-slate-800">{{ $request->title }}</span><span class="mt-1 block text-xs text-slate-400">{{ $request->created_at->format('Y-m-d') }}</span></span><x-badge :value="$request->status"/></a>@empty<x-empty-state :title="__('portal.no_requests')" :description="__('portal.no_requests_hint')" icon="maintenance"/>@endforelse</x-card>
    <section><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-slate-900">{{ __('portal.latest_announcements') }}</h2><a href="{{ route('tenant.announcements') }}" class="text-link text-xs">{{ __('app.view_all') }}</a></div><x-announcement-cards :announcements="$announcements"/></section>
</x-app-layout>
